### ISSUE TITLE
Genshin impact crashed after loading completed

### ISSUE THREAD

**Issue by warlice** [openfde/openfde#15]
Genshin impact crashed after the loading completed. 

**GPU**
radeon rx520
**Host OS**
Kylin V10SP1 or ubuntu 22.04

```
04-25 11:14:13.871  2673  2815 F DEBUG   : backtrace:
04-25 11:14:13.871  2673  2815 F DEBUG   :       00 pc 0000000000e8c893  /vendor/lib64/dri/libgallium_dri.so (BuildId: d0e9e4b8cd8dd97e3071c1c96fe2e62ae2f83dd3)
04-25 11:14:13.871  2673  2815 F DEBUG   :       01 pc 0000000000e95de0  /vendor/lib64/dri/libgallium_dri.so (BuildId: d0e9e4b8cd8dd97e3071c1c96fe2e62ae2f83dd3)
04-25 11:14:13.871  2673  2815 F DEBUG   :       02 pc 0000000000e48b96  /vendor/lib64/dri/libgallium_dri.so (BuildId: d0e9e4b8cd8dd97e3071c1c96fe2e62ae2f83dd3)
04-25 11:14:13.871  2673  2815 F DEBUG   :       03 pc 0000000000e49480  /vendor/lib64/dri/libgallium_dri.so (BuildId: d0e9e4b8cd8dd97e3071c1c96fe2e62ae2f83dd3)
04-25 11:14:13.871  2673  2815 F DEBUG   :       04 pc 0000000000ca4158  /vendor/lib64/dri/libgallium_dri.so (BuildId: d0e9e4b8cd8dd97e3071c1c96fe2e62ae2f83dd3)
04-25 11:14:13.871  2673  2815 F DEBUG   :       05 pc 00000000000d8814  /system/lib64/arm64/nb/libtcb.so (BuildId: 9db22213bae2d133f353c29c9fcf0d5f36f8f376)
04-25 11:14:13.871  2673  2815 F DEBUG   :       06 pc 0000000001423206  [anon:Mem_0x20000000]
```

Another situation is that  Genshin works fine on the Phytium x100 gpu.   and x100 gpu has the own opengl so, not to  use the gallium of mesa.

**Comment by 609386314** [comment]
A solution to the problem has been found：
[https://gitlab.freedesktop.org/mesa/mesa/-/issues/11148#note_2410145](url)

![Uploading Screenshot_20240517-091920_原神.png…]()

**Comment by 609386314** [comment]
how to debug:
  when not open debug in mesa, will crash at _mesa_reference_texobj_ funtion defined in external/mesa/src/mesa/main/texobj.c.
i don't known why has the invalid pointer crash, i try to open debug in mesa, a new crash arose at update_single_shader_texture_used funtion defined in external/mesa/src/mesa/main/uniforms.c. a assert crash "assert(unit < ARRAY_SIZE(prog->TexturesUsed))".

After some debugging, i can avoid above crash ,but lose some texture!
Like the patch below: 
--- a/src/mesa/main/uniform_query.cpp
+++ b/src/mesa/main/uniform_query.cpp
@@ -1565,7 +1565,8 @@ _mesa_uniform(GLint location, GLsizei count, const GLvoid *values,
FLUSH_VERTICES(ctx, _NEW_TEXTURE_OBJECT, 0);
flushed = true;
}
-- sh->Program->SamplerUnits[unit] = value;
++ unsigned maxTexturesUsed = ARRAY_SIZE(sh->Program->TexturesUsed);
++ sh->Program->SamplerUnits[unit] = value >= maxTexturesUsed ? maxTexturesUsed - 1 : value;
changed = true;

**Comment by 609386314** [comment]
skip_shader_opt_per_id;
     if (!skip_shader_opt) { 
--      optimize(*shader);
++      //optimize(*shader);
       if (r600::sfn_log.has_debug_flag(r600::SfnLog::steps)) {
          std::cerr << "Shader after optimization\n";
          shader->print(std

**Comment by warlice** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/11148#note_2410145

**Comment by warlice** [comment]
we merged the patch into our repo.

https://github.com/openfde/waydroid_android_external_mesa3d/commit/c6bd1caa9dba534504f4512a8f75717fe3bfe5b6

**Comment by warlice** [comment]
we merged the patch into our repo.

https://github.com/openfde/waydroid_android_external_mesa3d/commit/c6bd1caa9dba534504f4512a8f75717fe3bfe5b6

**Comment by warlice** [comment]
![image](https://github.com/openfde/openfde/assets/11641277/34e4215c-b134-45dc-b5ad-e7a2854e1216)
 
but， looks like lost the textures.

**Comment by warlice** [comment]
fixed by the below commit
https://github.com/openfde/waydroid_android_external_mesa3d/commit/bfb3deaf7fc215eac6f9aa31492425731ce78bad
