### ISSUE TITLE
In the fusion application Konsole, the esc key does not respond when the vim is edited

### ISSUE THREAD

**Issue by joe1111111** [openfde/openfde#8]
test steps：
1、Open  the fusion application Konsole
2、Use vim to open a file and enter the editing state
3、Use the esc key to exit the editing state

test results：
3、Exit failed

**Comment by joe1111111** [comment]
![Screenshot_20240510-153748_Fusion_Linux_Application](https://github.com/openfde/openfde/assets/26342937/0fccac52-0f6d-4ec0-af57-1ce1146c1312)

**Comment by ironlvxyy** [comment]
Esc is consumed as a back keyevent. Fixed using F8 as the back shortcut key instead.
[https://github.com/openfde/lineageos_android_frameworks_base/commit/4f2483b37b69de617777483b4b0933d3c7a47867](url)
