### ISSUE TITLE
景嘉微显卡：在Linux侧修改docx文档后，文档目录下和Linux主目录下打开同一文档内容不同

### ISSUE THREAD

**Issue by joe1111111** [openfde/openfde#96]
![fde_1723191037587](https://github.com/user-attachments/assets/90d0dfe0-24d5-42fc-aecc-67edae4febc1)
![fde_1723191019662](https://github.com/user-attachments/assets/bf916b7b-dbb2-4331-ba74-3ceb7b9932f0)

**Comment by warlice** [comment]
the code is not updated by accident. fixed by updating the mediaprovider repo
